sudo: false

language: node_js
node_js:
  - '4'
  - '5'
  - '6'

os:
- osx
- linux

install:
  - travis_retry npm install

script:
  - uname -a
  - node --version
  - npm --version
  - npm run ci-lint
  - npm run test
  - npm run check

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/3569d7edff0d38f93cd7"
    on_success: always
    on_failure: always
    on_start: false
